name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TESTING: "1"
      LINUX_IP: "172.17.0.1"
      DOCKER_HOST: "host.docker.internal"

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          cd /home/runner/work/HouseworkTracker/
          pytest
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy to my VM
        run: |
          ssh -o StrictHostKeyChecking=no lisa@mercuryweb01 << 'EOF'
          cd ~/HouseworkTracker
          git pull origin main
          docker stop houseworktracker || true
          docker rm houseworktracker || true
          docker build -t houseworktracker:latest .
          docker run -d --name houseworktracker -p 8000:8000 houseworktracker:latest
          EOF
