name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TESTING: "1"
      LINUX_IP: "172.17.0.1"
      DOCKER_HOST: "host.docker.internal"

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          cd /home/runner/work/HouseworkTracker/
          pytest
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Explicitly set SSH_AUTH_SOCK to point to the correct socket
      - name: Set SSH_AUTH_SOCK
        run: echo "SSH_AUTH_SOCK=/tmp/ssh-K5ryRXuQr65q/agent.50656" >> $GITHUB_ENV

      - name: Check SSH Agent
        run: |
          echo $SSH_AUTH_SOCK
          ssh-add -l

      # Test SSH key access to GitHub
      - name: Test SSH access to GitHub
        run: ssh -T git@github.com

      - name: Deploy to my VM
        run: |
          ssh -o StrictHostKeyChecking=no lisa@mercuryweb01 << 'EOF'
          cd ~/HouseworkTracker
          git pull origin main
          docker stop houseworktracker || true
          docker rm houseworktracker || true
          docker build -t houseworktracker:latest .
          docker run -d --name houseworktracker -p 8000:8000 houseworktracker:latest
          EOF
